services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: kingsleys_frontend
    restart: always

    depends_on:
      - backend

    labels:
      - "traefik.enable=true"

      # IMPORTANT
      - "traefik.docker.network=traefik"

      # Frontend ONLY (exclude API)
      - "traefik.http.routers.kingsleys_frontend.rule=Host(`dashboard.projectkingsleys.com`) && !PathPrefix(`/api`)"
      - "traefik.http.routers.kingsleys_frontend.entrypoints=websecure"
      - "traefik.http.routers.kingsleys_frontend.tls=true"
      - "traefik.http.routers.kingsleys_frontend.tls.certresolver=production"

      # Nginx inside frontend container
      - "traefik.http.services.kingsleys_frontend.loadbalancer.server.port=80"

    networks:
      - kingsleys_network
      - internal_network
      - traefik


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: kingsleys_backend
    restart: always

    env_file:
      - ./backend/.env

    labels:
      - "traefik.enable=true"

      # API routing
      - "traefik.http.routers.kingsleys_backend.rule=Host(`dashboard.projectkingsleys.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.kingsleys_backend.entrypoints=websecure"
      - "traefik.http.routers.kingsleys_backend.tls=true"
      - "traefik.http.routers.kingsleys_backend.tls.certresolver=production"

      # STRIP /api before sending to Express (IMPORTANT)
      - "traefik.http.middlewares.api-strip.stripprefix.prefixes=/api"
      - "traefik.http.routers.kingsleys_backend.middlewares=api-strip"

      # Express port
      - "traefik.http.services.kingsleys_backend.loadbalancer.server.port=5000"

    networks:
      - kingsleys_network
      - internal_network
      - traefik


networks:
  kingsleys_network:
    driver: bridge

  internal_network:
    external: true

  traefik:
    external: true