module.exports = [
  { id: 1, name: "Data Warehouse" },
  { id: 2, name: "Store Manager" },
  { id: 3, name: "Kingsleys Website" },
  { id: 4, name: "Kingsleys Mobile App" },
  { id: 5, name: "Data Manager" },
  { id: 6, name: "Store Inventory" },
  { id: 7, name: "Store Maintenance" },
  { id: 8, name: "Staff Training" },
  { id: 9, name: "Document Manager" },
  { id: 10, name: "Reports & Stats" },
  { id: 11, name: "Log Management" },
  { id: 12, name: "Monitoring" },
  { id: 13, name: "Menu Boards" },
  { id: 14, name: "Storage Manager" },
  { id: 15, name: "Marketing" },
  { id: 16, name: "Alerts / Notifications" },
  { id: 17, name: "Knowledge Base" },
];
